name: Deploy Docs

on:
  push:
    branches:
      - main
      - develop
      - feature/CW-126-storybook-setup

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install

      - name: Build Storybook
        run: bun run build-storybook
        env:
          DATABASE_URL: "postgresql://dummy:dummy@localhost:5432/dummy"
          CLERK_SECRET_KEY: "dummy_key"
          CLERK_FRONTEND_API: "dummy_api"
          WEBHOOK_SECRET: "dummy_secret"
          NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: "dummy_publishable_key"

      - name: Deploy storybook
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          bun run deploy-storybook -- --ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}