name: JEST TESTS

on:
  push:
    branches:
      - develop
      - main

  pull_request:
    branches:
      - develop
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: bun install
      - run: bun run test
