name: JEST TESTS

on:
  push:
    branches:
      - develop
      - main

  pull_request:
    branches:
      - develop
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Decrypt large secret
        run: ./decrypt_secret.sh
        env:
          TEST_SECRET: ${{ secrets.TEST }}
      - run: bun install
      - run: bun run test
