name: JEST TESTS

on:
  push:
    branches:
      - develop
      - main

  pull_request:
    branches:
      - develop
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        env:
          CLERK_FRONTEND_API: ${{ secrets.CLERK_FRONTEND_API }}
          WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
          UPLOADTHING_TOKEN: ${{ secrets.UPLOADTHING_TOKEN }}
      - run: bun install
      - run: bun run test
