name: CI/CD Pipeline

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

jobs:
  lint:
    name: Biome Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun run lint:force
      - run: bun run format:fix

  test:
    name: Vitest Tests
    runs-on: ubuntu-latest
    environment: TEST
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
      CLERK_FRONTEND_API: ${{ secrets.CLERK_FRONTEND_API }}
      WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
      CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      UPLOADTHING_TOKEN: ${{ secrets.UPLOADTHING_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun run test:unit

  code-climate:
    name: Code Climate
    runs-on: ubuntu-latest
    environment: TEST
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
      CLERK_FRONTEND_API: ${{ secrets.CLERK_FRONTEND_API }}
      WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
      UPLOADTHING_TOKEN: ${{ secrets.UPLOADTHING_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: bun run test:coverage
          coverageLocations: |
            ${{github.workspace}}/coverage/lcov.info:lcov
          debug: true
