# GitHub Actions
# https://docs.github.com/en/actions/using-workflows
name: CI

on:
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.3.0' # Especifique a versão do Node.js que você está usando

      - name: Install Bun
        run: npm install -g bun

      - name: Cache Bun
        uses: actions/cache@v3
        with:
          path: |
            ~/.bun
            bun.lockb
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}

      - name: Install dependencies
        run: bun install

      - name: Install Cypress
        run: bun cypress install

      - name: Run Cypress tests
        run: bun run cypress run
